import { ModalsProvider } from '@/contexts/modals'
import { AuthProvider } from '@/contexts/auth'
import './globals.css'

export const metadata = {
  title: 'ERP-Lab',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <ModalsProvider>
          <body>{children}</body>
        </ModalsProvider>
      </AuthProvider>
    </html>
  )
}
